import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface CanvasSection {
  id: string;
  title: string;
  description?: string;
  fields: Array<{
    id: string;
    label: string;
    value: string;
  }>;
}

export interface CanvasExportData {
  projectName: string;
  canvasName: string;
  exportDate: string;
  completionPercentage: number;
  sections: CanvasSection[];
  metadata?: {
    lastUpdated?: string;
    version?: string;
    [key: string]: any;
  };
}

/**
 * Generate beautiful PDF with proper formatting and sections
 */
export const exportToPDF = (data: CanvasExportData): void => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  let yPosition = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - 2 * margin;

  // Title Page
  doc.setFillColor(59, 130, 246); // Blue
  doc.rect(0, 0, pageWidth, 50, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text(data.canvasName, pageWidth / 2, 25, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(data.projectName, pageWidth / 2, 35, { align: "center" });

  // Info Box
  yPosition = 60;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Export Date: ${data.exportDate}`, margin, yPosition);
  yPosition += 6;
  doc.text(`Completion: ${data.completionPercentage}%`, margin, yPosition);
  yPosition += 6;
  if (data.metadata?.lastUpdated) {
    doc.text(`Last Updated: ${data.metadata.lastUpdated}`, margin, yPosition);
    yPosition += 6;
  }

  // Progress Bar
  yPosition += 5;
  const barWidth = 100;
  const barHeight = 6;
  doc.setDrawColor(200, 200, 200);
  doc.rect(margin, yPosition, barWidth, barHeight);
  doc.setFillColor(34, 197, 94); // Green
  doc.rect(
    margin,
    yPosition,
    (barWidth * data.completionPercentage) / 100,
    barHeight,
    "F"
  );

  yPosition += 15;

  // Sections
  data.sections.forEach((section, sectionIndex) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }

    // Section Header
    doc.setFillColor(243, 244, 246);
    doc.rect(margin, yPosition - 5, contentWidth, 12, "F");
    doc.setTextColor(31, 41, 55);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(section.title, margin + 3, yPosition + 3);
    yPosition += 12;

    if (section.description) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(107, 114, 128);
      const descLines = doc.splitTextToSize(
        section.description,
        contentWidth - 6
      );
      doc.text(descLines, margin + 3, yPosition);
      yPosition += descLines.length * 4 + 3;
    }

    // Fields Table
    const tableData = section.fields.map((field) => [
      field.label,
      field.value || "-",
    ]);

    autoTable(doc, {
      startY: yPosition,
      head: [["Field", "Value"]],
      body: tableData,
      margin: { left: margin, right: margin },
      theme: "grid",
      headStyles: {
        fillColor: [59, 130, 246],
        textColor: [255, 255, 255],
        fontSize: 10,
        fontStyle: "bold",
      },
      bodyStyles: {
        fontSize: 9,
        textColor: [31, 41, 55],
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251],
      },
      columnStyles: {
        0: { cellWidth: 50, fontStyle: "bold" },
        1: { cellWidth: contentWidth - 50 },
      },
      didDrawPage: (data) => {
        // Footer
        doc.setFontSize(8);
        doc.setTextColor(107, 114, 128);
        doc.text(
          `Page ${doc.getCurrentPageInfo().pageNumber}`,
          pageWidth / 2,
          doc.internal.pageSize.getHeight() - 10,
          { align: "center" }
        );
      },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 10;
  });

  // Footer on last page
  const pageCount = doc.getNumberOfPages();
  doc.setPage(pageCount);
  const finalY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(
    `Generated by Strategize+ on ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    finalY,
    { align: "center" }
  );

  // Save
  doc.save(
    `${sanitizeFilename(data.projectName)}-${sanitizeFilename(
      data.canvasName
    )}-${Date.now()}.pdf`
  );
};

/**
 * Utility: Sanitize filename
 */
const sanitizeFilename = (name: string): string => {
  return name
    .replace(/[^a-z0-9]/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
};
